name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Create env file
        run: |
          cd frontend
          echo "REACT_APP_TATUM_API_KEY=${{ secrets.REACT_APP_TATUM_API_KEY }}" > .env
          echo "REACT_APP_CSV_URL=${{ secrets.REACT_APP_CSV_URL }}" >> .env

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build
          branch: gh-pages 